# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainManager(object):
    def setupUi(self, MainManager):
        MainManager.setObjectName("MainManager")
        MainManager.resize(680, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainManager.sizePolicy().hasHeightForWidth())
        MainManager.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("view-history")
        MainManager.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(MainManager)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.newSnapshotPB = QtWidgets.QPushButton(MainManager)
        self.newSnapshotPB.setObjectName("newSnapshotPB")
        self.gridLayout_3.addWidget(self.newSnapshotPB, 0, 0, 1, 1)
        self.configurePB = QtWidgets.QPushButton(MainManager)
        self.configurePB.setObjectName("configurePB")
        self.gridLayout_3.addWidget(self.configurePB, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(503, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.lw = QtWidgets.QListWidget(MainManager)
        self.lw.setProperty("showDropIndicator", False)
        self.lw.setAlternatingRowColors(True)
        self.lw.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lw.setResizeMode(QtWidgets.QListView.Adjust)
        self.lw.setObjectName("lw")
        self.gridLayout_3.addWidget(self.lw, 1, 0, 1, 3)
        self.editBox = QtWidgets.QScrollArea(MainManager)
        self.editBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.editBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.editBox.setWidgetResizable(True)
        self.editBox.setObjectName("editBox")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 748, 326))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.editGroup = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.editGroup.setTitle("")
        self.editGroup.setObjectName("editGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.editGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aliasLabel = QtWidgets.QLabel(self.editGroup)
        self.aliasLabel.setObjectName("aliasLabel")
        self.horizontalLayout.addWidget(self.aliasLabel)
        self.aliasLE = QtWidgets.QLineEdit(self.editGroup)
        self.aliasLE.setInputMask("")
        self.aliasLE.setText("")
        self.aliasLE.setMaxLength(30)
        self.aliasLE.setFrame(True)
        self.aliasLE.setObjectName("aliasLE")
        self.horizontalLayout.addWidget(self.aliasLE)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonCancelMini = QtWidgets.QPushButton(self.editGroup)
        self.buttonCancelMini.setMinimumSize(QtCore.QSize(22, 22))
        self.buttonCancelMini.setMaximumSize(QtCore.QSize(22, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonCancelMini.setFont(font)
        self.buttonCancelMini.setText("X")
        self.buttonCancelMini.setObjectName("buttonCancelMini")
        self.horizontalLayout.addWidget(self.buttonCancelMini)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.editGroup)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.editGroup, 0, 0, 1, 1)
        self.editBox.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.editBox, 2, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(298, 21, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.opTypeLabel = QtWidgets.QLabel(MainManager)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.opTypeLabel.setFont(font)
        self.opTypeLabel.setAutoFillBackground(False)
        self.opTypeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.opTypeLabel.setTextFormat(QtCore.Qt.RichText)
        self.opTypeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.opTypeLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.opTypeLabel.setObjectName("opTypeLabel")
        self.horizontalLayout_3.addWidget(self.opTypeLabel)
        self.progressBar = QtWidgets.QProgressBar(MainManager)
        self.progressBar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 0, 1, 3)
        self.takeBackAction = QtWidgets.QAction(MainManager)
        icon1 = QtGui.QIcon.fromTheme("resource-calendar-insert")
        self.takeBackAction.setIcon(icon1)
        self.takeBackAction.setObjectName("takeBackAction")
        self.copyAction = QtWidgets.QAction(MainManager)
        self.copyAction.setObjectName("copyAction")

        self.retranslateUi(MainManager)
        QtCore.QMetaObject.connectSlotsByName(MainManager)

    def retranslateUi(self, MainManager):
        _translate = QtCore.QCoreApplication.translate
        MainManager.setWindowTitle(_translate("MainWindow", "History Manager"))
        self.newSnapshotPB.setText(_translate("MainWindow", "New Snapshot"))
        self.configurePB.setText(_translate("MainWindow", "History Settings"))
        self.lw.setSortingEnabled(True)
        self.aliasLabel.setText(_translate("MainWindow", "Alias :"))
        self.buttonCancelMini.setToolTip(_translate("MainWindow", "Cancel"))
        self.opTypeLabel.setText(_translate("MainWindow", "- Loading Pisi History"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.takeBackAction.setText(_translate("MainWindow", "Take back to this point"))
        self.copyAction.setText(_translate("MainWindow", "Copy"))
